sle_repositories: {
  "{SLES 12 SP3 Updates x86_64}": "obs://SUSE:SLE-12-SP3:Update/SLES",
  "{SLES 12 SP3 x86_64}": "obs://SUSE:SLE-12-SP3:GA/SLES",
  "{SLE 12 SP3 SDK x86_64}": "obs://SUSE:SLE-12-SP3:GA/SDK",
  "{SLE 12 SP3 SDK Updates x86_64}": "obs://SUSE:SLE-12-SP3:Update/SDK",
  "{SLES 12 SP2 Updates x86_64}": "obs://SUSE:SLE-12-SP3:Update/SLES",
  "{SLES 12 SP2 x86_64}": "obs://SUSE:SLE-12-SP3:GA/SLES",
  "{SLE 12 SP2 SDK x86_64}": "obs://SUSE:SLE-12-SP3:GA/SDK",
  "{SLE 12 SP2 SDK Updates x86_64}": "obs://SUSE:SLE-12-SP3:Update/SDK",
  "{SLES 12 SP1 Updates x86_64}": "obs://SUSE:SLE-12-SP3:Update/SLES",
  "{SLES 12 SP1 x86_64}": "obs://SUSE:SLE-12-SP3:GA/SLES",
  "{SLE 12 SP1 SDK x86_64}": "obs://SUSE:SLE-12-SP3:GA/SDK",
  "{SLE 12 SP1 SDK Updates x86_64}": "obs://SUSE:SLE-12-SP3:Update/SDK",
  "{SLES 12 Updates x86_64}": "obs://SUSE:SLE-12-SP3:Update/SLES",
  "{SLES 12 x86_64}": "obs://SUSE:SLE-12-SP3:GA/SLES",
  "{SLE 12 SDK x86_64}": "obs://SUSE:SLE-12-SP3:GA/SDK",
  "{SLE 12 SDK Updates x86_64}": "obs://SUSE:SLE-12-SP3:Update/SDK"
}
sle_dependencies_repository : "obs://SUSE:SLE-12-SP3:Update/OBS_Deps"
